# Generated by Django 4.2.29 on 2026-03-26 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=255)),
                ('severity', models.CharField(default='Mild', max_length=32)),
                ('symptoms', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('precautions', models.JSONField(default=list)),
                ('medications', models.JSONField(default=list)),
                ('when_to_see_doctor', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('user_symptoms', models.TextField(blank=True)),
                ('symptom_cards', models.JSONField(default=list)),
                ('summary', models.CharField(default='Medical diagnosis report', max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], default='completed', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
